FROM ubuntu:20.04
LABEL owner="balaji"
LABEL version="1.0"
ARG VERSION="1.2.9"
RUN apt update && apt install nginx unzip jq curl wget
COPY index.html /var/www/html/index.nginx-debian.html
COPY style.css /var/www/html/style.css
COPY scorekeeper.js /var/www/html/scorekeeper.js
ADD https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip /usr/local/bin/terraform.zip
RUN cd /usr/local/bin/ && unzip terraform.zip && rm -f *.zip