FROM ubuntu:20.04
LABEL owner="balaji"
LABEL version="1.0"
RUN apt update && apt install nginx unzip jq curl wget
COPY index.html /var/www/html/index.nginx-debian.html
COPY style.css /var/www/html/style.css
COPY scorekeeper.js /var/www/html/scorekeeper.js
